apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::553021162727:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T19:45:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1278"
  uid: c34311a7-6b32-4cf8-9043-a9a039e14dce
