apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::922132847731:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-H4R32FXC5900
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-24T17:12:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1498"
  uid: c1abb40c-474a-470f-8ade-9d76256d25b1
